Makes both files more functional
Now almost all db functions require the name of dbFile to work.
Thanks to type hinting and mypy, I resolved the potential issue
  above change created in call sign if read_task which would have
  tripped any map() functions. Used functools to resolve it
Also, since type hinting support isn't robust, I am getting the
  following error from mypy (beside the hiccup on pytest)
`model\db.py:132: error: No overload variant of "map" matches argument
types [functools.partial[db.aTask*], Any]`
  apparently, mypy is having a hiccup due to mix of map and partial
  function

 On branch master
 Your branch is ahead of 'origin/master' by 1 commit.
   (use "git push" to publish your local commits)

 Changes to be committed:
	modified:   controller.py
	modified:   model/db.py

 Untracked files:
	view/superdom.js